### ISSUE TITLE
自定义函数和水位线表无法解析

### ISSUE THREAD

**Issue by SinyoWong** [HamaWhiteGG/flink-sql-lineage#3]
在执行计划中，
FlinkLogicalTableFunctionScan
和
LogicalWatermarkAssigner
两种类型的RelNode无法解析获取到源字段

**Comment by HamaWhiteGG** [comment]
thanks for your question。
此问题已经添加，详见 https://github.com/HamaWhiteGG/flink-sql-lineage/tree/2.0.0

文档在README的第"五、Flink其他高级语法支持"章节。

**Comment by aiwenmo** [comment]
感谢老师的分享与贡献，该修复已实装 Dinky。
[[Optimization-1326][client] Optimize lineage to support watermark and udf](https://github.com/DataLinkDC/dlink/pull/1327)
