### ISSUE TITLE
当where中包含字段等于常量时，会把源字段优化成常量，导致丢失改字段的血缘关系

### ISSUE THREAD

**Issue by aiwenmo** [HamaWhiteGG/flink-sql-lineage#32]
当输入以下 FlinkSQL 时:
`
CREATE TABLE demo_log_01 (
    user_id BIGINT,
    item_id BIGINT,
    behavior STRING,
    dt STRING,
    hh STRING
) WITH (
  'connector' = 'datagen',
  'rows-per-second' = '1'
);
CREATE TABLE demo_log_02 (
    user_id BIGINT,
    item_id BIGINT,
    behavior STRING,
    dt STRING,
    hh STRING
) WITH (
  'connector' = 'datagen',
  'rows-per-second' = '1'
);
CREATE TABLE demo_log_05 (
    user_id BIGINT,
    item_id BIGINT,
    behavior STRING,
    dt STRING,
    hh STRING
) WITH (
  'connector' = 'print'
);
insert into demo_log_05
select a.user_id,b.item_id,b.behavior,a.dt,a.hh from 
(select  user_id,item_id,behavior,dt,hh from demo_log_01 where dt='2023-17-02') a 
left join 
(select  user_id,item_id,behavior,dt,hh from demo_log_02) b
on a.user_id = b.user_id

`

**Comment by aiwenmo** [comment]
获得错误的血缘关系图：
![image](https://user-images.githubusercontent.com/32723967/221219283-b5815b34-58ed-45ed-8205-1c1e166b0262.png)

**Comment by aiwenmo** [comment]
原因是在where里dt等于常量，然后优化器直接是把常量插入到demo_log_05表。 本质来说demo_log_05,dt 是来自于一个常量的。
![image](https://user-images.githubusercontent.com/32723967/221220453-78a78ee4-a056-4def-8ab1-b26e2b5fd064.png)

**Comment by HamaWhiteGG** [comment]
you can see the test case https://github.com/HamaWhiteGG/flink-sql-lineage/blob/release-4.0.0/lineage-flink1.16.x/src/test/java/com/hw/lineage/flink/paimon/PaimonTest.java

![99953205-32C4-40BF-8949-2DB2F10834B6](https://user-images.githubusercontent.com/97529774/226981544-b72e8851-8ef9-4ec5-aac6-eaae8a49c57c.png)
