### ISSUE TITLE
语法中如果有window tvf会返回空

### ISSUE THREAD

**Issue by y0908105023** [HamaWhiteGG/flink-sql-lineage#51]

**Comment by HamaWhiteGG** [comment]
@y0908105023 
Thanks, I support windowing TVF lineage analysis, see unit test for details [TvfTest.java](https://github.com/HamaWhiteGG/flink-sql-lineage/pull/58/commits/edf1e5d01bd496ef54ee90c872ea7c7e4b1cadc5#diff-1c4e8db8675db0ae58d473725fed12eeee233159d992495dada716fea1b55336)
