### ISSUE TITLE
UDTF 函数使用别名时解析异常

### ISSUE THREAD

**Issue by hjfrank1991** [HamaWhiteGG/flink-sql-lineage#66]
INSERT INTO
  dwd_hudi_users
SELECT
  length,
  name,
  word as company_name,
  birthday,
  ts,
  DATE_FORMAT(birthday, 'yyyyMMdd')
FROM
  ods_mysql_users,
  LATERAL TABLE (my_split_udtf (name))
作者给的这个示例是可以解析出血缘关系;
如果sql更换为
INSERT INTO
  dwd_hudi_users
SELECT
  length,
  column1 as name,
  word as company_name,
  birthday,
  ts,
  DATE_FORMAT(birthday, 'yyyyMMdd')
FROM
  ods_mysql_users,
  LATERAL TABLE (my_split_udtf (name)) as T (column1)
解析此sql是用2.0.0的RelMdColumnOrigins 会抛出 org.apache.flink.table.planner.plan.nodes.logical.FlinkLogicalCalc cannot be cast to org.apache.calcite.rel.core.TableFunctionScan异常
使用main的RelMdColumnOrigins 
mq.getColumnOrigins(rel.getRight(), iOutputColumn - nLeftColumns)
mappings 为null 并且 rel.getInputs().isEmpty() 返回set size 0
source column无法解析

**Comment by hjfrank1991** [comment]
如果LATERAL TABLE (my_split_udtf (cast(name as string))) as T (column1) UDTF中使用了cast 或者别的函数也会在
![image](https://github.com/HamaWhiteGG/flink-sql-lineage/assets/30491745/0337d346-16f9-4638-a5e6-69115e6d4fbf)
此处报错org.apache.calcite.rex.RexCall cannot be cast to org.apache.calcite.rex.RexFieldAccess

**Comment by HamaWhiteGG** [comment]
> 如果LATERAL TABLE (my_split_udtf (cast(name as string))) as T (column1) UDTF中使用了cast 或者别的函数也会在 ![image](https://user-images.githubusercontent.com/30491745/237306824-0337d346-16f9-4638-a5e6-69115e6d4fbf.png) 此处报错org.apache.calcite.rex.RexCall cannot be cast to org.apache.calcite.rex.RexFieldAccess

Thanks, when the function is used in the UDF, it does not support it. I just added this function point.
the test case is [TableFunctionTest#testInsertSelectWithFunctionInUDTF](https://sourcegraph.com/github.com/HamaWhiteGG/flink-sql-lineage@hotfix-66/-/blob/lineage-flink1.16.x/src/test/java/com/hw/lineage/flink/tablefuncion/TableFunctionTest.java)
![image](https://github.com/HamaWhiteGG/flink-sql-lineage/assets/97529774/9fb1b723-85fd-480b-bca8-d826b48afff1)

**Comment by HamaWhiteGG** [comment]
> INSERT INTO dwd_hudi_users SELECT length, name, word as company_name, birthday, ts, DATE_FORMAT(birthday, 'yyyyMMdd') FROM ods_mysql_users, LATERAL TABLE (my_split_udtf (name)) 作者给的这个示例是可以解析出血缘关系; 如果sql更换为 INSERT INTO dwd_hudi_users SELECT length, column1 as name, word as company_name, birthday, ts, DATE_FORMAT(birthday, 'yyyyMMdd') FROM ods_mysql_users, LATERAL TABLE (my_split_udtf (name)) as T (column1) 解析此sql是用2.0.0的RelMdColumnOrigins 会抛出 org.apache.flink.table.planner.plan.nodes.logical.FlinkLogicalCalc cannot be cast to org.apache.calcite.rel.core.TableFunctionScan异常 使用main的RelMdColumnOrigins mq.getColumnOrigins(rel.getRight(), iOutputColumn - nLeftColumns) mappings 为null 并且 rel.getInputs().isEmpty() 返回set size 0 source column无法解析

The output of my_split_udtf is two fields(word and length), but your case has only one field, please check to see if this is correct. 

There are already test cases for aliases. [TableFunctionTest#testInsertSelectLeftJoinAndRenameUDTF](https://sourcegraph.com/github.com/HamaWhiteGG/flink-sql-lineage@hotfix-66/-/blob/lineage-flink1.16.x/src/test/java/com/hw/lineage/flink/tablefuncion/TableFunctionTest.java?L102:17&popover=pinned)

<img width="900" alt="image" src="https://github.com/HamaWhiteGG/flink-sql-lineage/assets/97529774/3bfef7f7-e922-41d5-960f-68f6f5eca407">

**Comment by hjfrank1991** [comment]
> > INSERT INTO dwd_hudi_users SELECT length, name, word as company_name, birthday, ts, DATE_FORMAT(birthday, 'yyyyMMdd') FROM ods_mysql_users, LATERAL TABLE (my_split_udtf (name)) 作者给的这个例子是可以解析出血缘的关系; 如果sql更改为INSERT INTO dwd_hudi_users SELECT length, column1 as name, word as company_name, birthday, ts, DATE_FORMAT(birthday, 'yyyyMMdd') FROM ods_mysql_users, LATERAL TABLE (my_split_udtf (name)) as T (column1) 解析此sql是使用2.0.0的RelMdColumnOrigins会抛出org.apache.flink.table.planner.plan.nodes.logical.FlinkLogicalCalc cannot be cast to org.apache.calcite.rel.core.TableFunctionScan异常使用main的RelMdColumnOrigins mq.getColumnOrigins( rel.getRight(), iOutputColumn - nLeftColumns) mappings 为null 并rel.getInputs().isEmpty() 返回set size 0 source column无法解析
> 
> my_split_udtf 的输出是两个字段（word 和 length），但是你的案例只有一个字段，请检查是否正确。
> 
> 已经有别名的测试用例。[TableFunctionTest#testInsertSelectLeftJoinAndRenameUDTF](https://sourcegraph.com/github.com/HamaWhiteGG/flink-sql-lineage@hotfix-66/-/blob/lineage-flink1.16.x/src/test/java/com/hw/lineage/flink/tablefuncion/TableFunctionTest.java?L102:17&popover=pinned)
> 
> <img alt="图像" width="900" src="https://user-images.githubusercontent.com/97529774/237484882-3bfef7f7-e922-41d5-960f-68f6f5eca407.png">
我知道呢个地方出问题了,
你的例子中是
![image](https://github.com/HamaWhiteGG/flink-sql-lineage/assets/30491745/e4100254-7ffc-4bfa-9f8f-e16f70a7199b)
是new_word as company_name
我的例子中是 UDTF函数生成的新列 as UDTF函数的参数列;
所以 你可以试试这样:
![image](https://github.com/HamaWhiteGG/flink-sql-lineage/assets/30491745/eb57bc62-9dbc-437d-a0b8-bb1b33273390)

**Comment by hjfrank1991** [comment]
我们需要使用rel.getRight() 可能是TableFunctionScan 或者使用 rel.getRight().getInputs() 寻找TableFunctionScan
